Repository atlp-rwanda/dynamites-ecomm-be, pull requests merged in 2024-06, with the labels that each got.

#115 Ft order tracking #91
  src/__test__/orderController.test.ts
  src/controller/orderController.ts
  src/database/models/orderEntity.ts
  src/docs/cartDocs.ts
  src/routes/index.ts
  src/routes/orderRoutes.ts
Labels: backend, Ready for TTL Review

#109 Ft user should ask to chat-bot #108
  package.json
  src/__test__/cartController.test.ts
  src/__test__/chatbot.test.ts
  src/__test__/chatbotService.test.ts
  src/__test__/npl.test.ts
  src/__test__/service.test.ts
  src/app.ts
  src/controller/cartController.ts
  src/controller/chatbotController.ts
  src/controller/productController.ts
  src/controller/serviceController.ts
  src/database/models/chatbotModel.ts
  src/database/models/serviceEntity.ts
  src/docs/cartDocs.ts
  src/docs/chatbotDocs.ts
  src/docs/reviewDocs.ts
  src/docs/serviceDocs.ts
  src/middlewares/errorHandler.ts
  src/routes/chatbotRoutes.ts
  src/routes/index.ts
  src/routes/serviceRoutes.ts
  src/service/chatbotService.ts
  src/service/serviceService.ts
  src/utilis/nlp.ts
  src/utils/couponCalculator.ts
Labels: backend, Ready for TTL Review

#118 94 buyer should be able to pay via mtn mobile money
  .github/workflows/workflow_for_ecomm.yml
  .gitignore
  package-lock.json
  package.json
  src/__test__/Momo.test.ts
  src/__test__/payment.test.ts
  src/controller/buyerController.ts
  src/controller/buyerWishlistController.ts
  src/docs/buyerDocs.ts
  src/middlewares/errorHandler.ts
  src/routes/buyerRoutes.ts
Labels: backend

#92 feat: Implement Product Lifecycle Notification System
  package-lock.json
  package.json
  src/Notification.vendor/EmailSendor.ts
  src/Notification.vendor/event.services.ts
  src/Notification.vendor/message.Templete.ts
  src/Notification.vendor/node.cron.services.ts
  src/__test__/notification.vendor.test.ts
  src/controller/cartController.ts
  src/controller/notificationController.ts
  src/controller/orderController.ts
  src/controller/productController.ts
  src/database/models/inbox_notification.ts
  src/database/models/index.ts
  src/docs/notification.vendor.Docs.ts
  src/index.ts
  src/routes/index.ts
  src/routes/notificationRoutes.ts
Labels: backend, WIP

#127 Fix social logins
  src/controller/userController.ts
  src/middlewares/passport-setup.ts
  src/routes/auth-routes.ts
  src/routes/userRoutes.ts
Labels: backend, Ready for TTL Review
