Repository atlp-rwanda/dynamites-ecomm-be, pull requests merged in 2024-05, with the labels that each got.

#44 Removed unnecesary type annotation and console logs in errorHandler
  src/middlewares/errorHandler.ts
Labels: bug, backend

#42 40 utility implement account confirmation password reset emails with templates
  package-lock.json
  package.json
  src/emails/index.ts
  src/emails/templates/confirm.html
  src/emails/templates/reset.html
Labels: backend

#41 #28 user-register
  .eslintrc.json
  .github/workflows/workflow_for_ecomm.yml
  .gitignore
  package-lock.json
  package.json
  src/__test__/index.test.ts
  src/__test__/testSetup.ts
  src/__test__/userController.test.ts
  src/app.ts
  src/controller/user.ts
  src/controller/userController.ts
  src/database/index.ts
  src/database/models/index.ts
  src/database/models/user.ts
  src/database/models/userModel.ts
  src/docs/userRegisterDocs.ts
  src/emails/index.ts
  src/index.ts
  src/router.ts
  src/routes/userRoutes.ts
Labels: backend

#49 Solved Email send failed error when trying to verify users
  .github/workflows/workflow_for_ecomm.yml
  src/emails/index.ts
  src/emails/templates/confirm.html
Labels: bug, backend

#46 #34 Add Role Based Access Control
  .github/workflows/workflow_for_ecomm.yml
  package-lock.json
  package.json
  src/__test__/roles.test.ts
  src/__test__/testSetup.ts
  src/__test__/userController.test.ts
  src/app.ts
  src/controller/roleController.ts
  src/controller/userController.ts
  src/database/models/index.ts
  src/database/models/roleEntity.ts
  src/database/models/userModel.ts
  src/docs/roleDocs.ts
  src/docs/swaggerconfig.ts
  src/emails/index.ts
  src/index.ts
  src/middlewares/authorize.ts
  src/middlewares/roleSchema.ts
  src/routes/index.ts
  src/routes/roleRoutes.ts
  tsconfig.json
Labels: backend

#47 Ft authenticate user #29
  package-lock.json
  package.json
  src/__test__/testSetup.ts
  src/__test__/userController.test.ts
  src/app.ts
  src/controller/roleController.ts
  src/controller/userController.ts
  src/database/models/userModel.ts
  src/docs/userAuth.ts
  src/middlewares/passport-setup.ts
  src/routes/userRoutes.ts
  tsconfig.json
Labels: documentation, backend

#59 Implement Two-Factor Authentication for Vendors #31
  .github/workflows/workflow_for_ecomm.yml
  package-lock.json
  package.json
  src/__test__/userController.test.ts
  src/controller/userController.ts
  src/controller/verification.js
  src/database/models/userModel.ts
  src/docs/2Fadocs.ts
  src/emails/mailer.ts
  src/emails/templates/2fa.html
  src/routes/userRoutes.ts
Labels: backend, WIP

#63 add new tests for buyers login
  .github/workflows/workflow_for_ecomm.yml
  package-lock.json
  package.json
  src/__test__/testSetup.ts
  src/__test__/userController.test.ts
  src/controller/userController.ts
  src/database/models/userModel.ts
  src/emails/mailer.ts
  src/middlewares/errorHandler.ts
Labels: backend

#62 Manage product
  package.json
  src/__test__/category.test.ts
  src/__test__/product.test.ts
  src/__test__/testSetup.ts
  src/__test__/userController.test.ts
  src/app.ts
  src/controller/categoryController.ts
  src/controller/productController.ts
  src/controller/userController.ts
  src/database/models/categoryEntity.ts
  src/database/models/index.ts
  src/database/models/productEntity.ts
  src/database/models/roleEntity.ts
  src/database/models/userModel.ts
  src/docs/2Fadocs.ts
  src/docs/categoryDocs.ts
  src/docs/productDoc.ts
  src/docs/userAuth.ts
  src/docs/userRegisterDocs.ts
  src/middlewares/authorize.ts
  src/middlewares/errorHandler.ts
  src/middlewares/isLoggedIn.ts
  src/middlewares/passport-setup.ts
  src/routes/categoryRoutes.ts
  src/routes/index.ts
  src/routes/productRoutes.ts
  src/routes/userRoutes.ts
Labels: backend, WIP

#53 update user profile
  .env.example
  .github/workflows/workflow_for_ecomm.yml
  package-lock.json
  package.json
  src/__test__/userController.test.ts
  src/controller/userController.ts
  src/database/models/roleEntity.ts
  src/database/models/userModel.ts
  src/docs/userRegisterDocs.ts
  src/routes/userRoutes.ts
Labels: backend, WIP

#73 #54 Buyer should be able to get a single product
  src/__test__/buyerController.test.ts
  src/__test__/testSetup.ts
  src/controller/buyerController.ts
  src/database/models/productEntity.ts
  src/docs/buyerDocs.ts
  src/routes/buyerRoutes.ts
  src/routes/index.ts
Labels: backend

#66 36 Ft admin deactivate activate
  src/__test__/changeStatus.test.ts
  src/__test__/testSetup.ts
  src/app.ts
  src/controller/changestatusController.ts
  src/controller/userController.ts
  src/docs/deactive_active.ts
  src/middlewares/revokeAccess.ts
  src/routes/userRoutes.ts
Labels: backend

#69 User is able to see recommended products
  src/__test__/product.test.ts
  src/__test__/testSetup.ts
  src/controller/productController.ts
  src/controller/userController.ts
  src/docs/productDoc.ts
  src/routes/productRoutes.ts
Labels: backend

#75 buyer be able to view available product
  src/__test__/product.test.ts
  src/controller/productController.ts
  src/docs/productDoc.ts
  src/routes/productRoutes.ts
Labels: backend

#90 created a new branch for solving emails
  package.json
  src/controller/userController.ts
Labels: bug, backend, Ready for TTL Review

#74 Implemented product availability get and update
  src/__test__/product.test.ts
  src/__test__/testSetup.ts
  src/controller/productController.ts
  src/docs/productDoc.ts
  src/middlewares/availabilityValidator.ts
  src/middlewares/productAvailabilityWatch.ts
  src/routes/productRoutes.ts
Labels: backend, Ready for TTL Review

#83 Buyer should be able to manage cart
  .github/workflows/workflow_for_ecomm.yml
  README.md
  package.json
  src/__test__/buyerController.test.ts
  src/__test__/cartController.test.ts
  src/__test__/changeStatus.test.ts
  src/__test__/product.test.ts
  src/__test__/testSetup.ts
  src/controller/cartController.ts
  src/controller/changestatusController.ts
  src/controller/productController.ts
  src/controller/roleController.ts
  src/controller/userController.ts
  src/controller/verification.js
  src/database/models/cartEntity.ts
  src/database/models/index.ts
  src/docs/cartDocs.ts
  src/docs/deactive_active.ts
  src/docs/productDoc.ts
  src/docs/userRegisterDocs.ts
  src/emails/index.ts
  src/emails/mailer.ts
  src/emails/templates/2fa.html
  src/emails/templates/confirm.html
  src/emails/templates/reset.html
  src/middlewares/errorHandler.ts
  src/middlewares/revokeAccess.ts
  src/routes/buyerRoutes.ts
  src/routes/cartRoutes.ts
  src/routes/index.ts
  src/routes/productRoutes.ts
  src/routes/roleRoutes.ts
Labels: backend, Ready for TTL Review

#95 Recover passowrd feature
  .github/workflows/PULL_REQUEST_TEMPLATE.MD
  README.md
  package-lock.json
  package.json
  src/__test__/userController.test.ts
  src/controller/userController.ts
  src/docs/userRegisterDocs.ts
  src/routes/userRoutes.ts
Labels: Ready for TTL Review

#98 Fix Deployment Issues by Updating Configuration Settings
  .github/PULL_REQUEST_TEMPLATE.MD
  src/app.ts
  src/config/db.ts
  src/index.ts
Labels: Ready for TTL Review

#99 created coupons
  src/__test__/coupon.test.ts
  src/controller/couponController.ts
  src/controller/productController.ts
  src/database/models/couponEntity.ts
  src/docs/couponDocs.ts
  src/routes/couponRoute.ts
  src/routes/index.ts
  src/utils/couponCalculator.ts
Labels: backend, Ready for TTL Review

#103 changed testsetup to make sure database is cleaned before running eve…
  .github/workflows/workflow_for_ecomm.yml
  package.json
  src/__test__/testSetup.ts
Labels: bug

#80 searchProducts
  package.json
  src/__test__/searchProduct.test.ts
  src/app.ts
  src/controller/searchProducts.ts
  src/docs/searchProduct.ts
  src/middlewares/validateSearchParams.ts
  src/routes/searchRoutes.ts
Labels: backend, Ready for TTL Review

#72 update profile
  package.json
  src/__test__/userController.test.ts
  src/controller/userController.ts
  src/docs/userRegisterDocs.ts
  src/routes/userRoutes.ts
Labels: backend, Ready for TTL Review

#106 A buyer is now to pay via stripe
  src/__test__/payment.test.ts
  src/controller/buyerController.ts
  src/database/models/orderEntity.ts
  src/docs/buyerDocs.ts
  src/middlewares/errorHandler.ts
  src/routes/buyerRoutes.ts
Labels: backend, Ready for TTL Review

#104 Buyer should be able to provide a review#89
  src/__test__/review.test.ts
  src/config/db.ts
  src/controller/productController.ts
  src/controller/reviewController.ts
  src/database/models/productEntity.ts
  src/database/models/reviewEntity.ts
  src/docs/reviewDocs.ts
  src/routes/index.ts
  src/routes/reviewRoutes.ts
Labels: backend, Ready for TTL Review

#114 #113 Fix swagger documentation of the review task
  src/docs/reviewDocs.ts
Labels: bug, Ready for TTL Review

#117 #116 Fix failing create review function
  src/__test__/review.test.ts
  src/controller/reviewController.ts
  src/docs/reviewDocs.ts
  src/middlewares/createReviewSchema.ts
Labels: bug, Ready for TTL Review

#110 Dockerize the Project for Easy Deployment
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  src/config/db.ts
Labels: backend, Ready for TTL Review
