Repository atlp-rwanda/dynamites-ecomm-be, pull requests merged in 2024-07, with the labels that each got.

#133 fix redirect frontend url
  src/routes/auth-routes.ts
Labels: backend, Ready for TTL Review

#137 granted admin acess
  package-lock.json
  src/routes/checkoutRoutes.ts
Labels: backend, Ready for TTL Review

#139 correcting password reset
  src/controller/userController.ts
Labels: bug, backend

#143 Fixed user type
  package-lock.json
  src/__test__/Momo.test.ts
  src/controller/buyerController.ts
  src/controller/userController.ts
Labels: bug, backend, Ready for TTL Review

#144 Create BestSeller controllers
  src/__test__/product.test.ts
  src/controller/productController.ts
  src/docs/productDoc.ts
  src/routes/productRoutes.ts
Labels: backend, Ready for TTL Review

#145 Fix: implement endpoint for retrieving chart data
  src/__test__/category.test.ts
  src/__test__/userController.test.ts
  src/controller/categoryController.ts
  src/controller/userController.ts
  src/database/models/userModel.ts
  src/docs/categoryDocs.ts
  src/docs/userRegisterDocs.ts
  src/emails/index.ts
  src/routes/categoryRoutes.ts
  src/routes/userRoutes.ts
Labels: Ready for TTL Review

#147 Implement get client api address and location
  .github/workflows/workflow_for_ecomm.yml
  package-lock.json
  src/__test__/Momo.test.ts
  src/__test__/category.test.ts
  src/__test__/orderController.test.ts
  src/__test__/payment.test.ts
  src/controller/cartController.ts
  src/controller/categoryController.ts
  src/controller/productController.ts
  src/database/models/orderEntity.ts
  src/docs/categoryDocs.ts
  src/routes/categoryRoutes.ts
Labels: backend, Ready for TTL Review

#149 Fix: fix bug in search functionality
  src/__test__/searchProduct.test.ts
  src/controller/searchProducts.ts
  src/docs/searchProduct.ts
  src/middlewares/validateSearchParams.ts
Labels: Ready for TTL Review

#152 Add vendors name and product category in best selling response
  src/controller/productController.ts
Labels: backend, Ready for TTL Review

#156 Implement API endpoint to fetch products belonging to a specific vendor
  src/__test__/product.test.ts
  src/controller/productController.ts
  src/docs/productDoc.ts
  src/routes/productRoutes.ts
Labels: backend, Ready for TTL Review

#157 Fix: Product details endpoint
  src/__test__/review.test.ts
  src/controller/buyerController.ts
  src/controller/reviewController.ts
  src/routes/buyerRoutes.ts
Labels: Ready for TTL Review

#161 Fix: Return vendor on product details endpoint
  src/controller/buyerController.ts
  src/controller/cartController.ts
Labels: backend, Ready for TTL Review

#159 fix: the Admin should get more details about coupons
  src/__test__/category.test.ts
  src/__test__/coupon.test.ts
  src/controller/categoryController.ts
  src/controller/couponController.ts
  src/database/models/couponEntity.ts
  src/docs/couponDocs.ts
  src/routes/couponRoute.ts
Labels: backend, Ready for TTL Review

#165 Fix: Orders
  src/controller/cartController.ts
  src/routes/checkoutRoutes.ts
Labels: backend
